# Error

TypeError: unhashable type: 'numpy.ndarray'

- hash(object): object의 저장된 내용을 기준으로 한 개의 정수를 생성하여 반환하는 함수
- https://analytics4everything.tistory.com/138 참고

- By definition, a dictionary key needs to be hashable. An object is hashable if it has a hash value that remains the same during its lifetime. A hash value is an integer Python uses to compare dictionary keys while looking at a dictionary.

- We raise the error because the elements of the array is a ndarray array object, and Ndarray objects are not hashable.

Solution
- We separate the multi-dimensional array into its component arrays and add their values to the set to solve this error.

You can add a numpy array directly to a set using the update() method. You cannot add a multi-dimensional ndarray directly to a set, you have to iterate over the ndarray and add each component array to the set using update().

If you want to use the values in a ndarray as keys in a dictionary, you have to extract the values from the array using the indexing operator [].

# Introduction

- 분류 : 답이 정해져있음 (은행이 대출 신청자들을 나눠서 돈을 빌려줌 -> 돈을 빌려줬어야 했다 아니다)
- 군집 : 답이 정해져있지 않음(사과를 품질에 따라 3개로 나눠? 5개로 나눠? -> 어떤 게 정답이라고 말하기 어려움)

## Numpy 복습

In [20]:
import numpy as np

- np.array
- array.shape

In [21]:
array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 arry 형태: ', array1.shape)

array1 type:  <class 'numpy.ndarray'>
array1 arry 형태:  (3,)


In [23]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type: ', type(array2))
print('array2 arry 형태: ', array2.shape)

array2 type:  <class 'numpy.ndarray'>
array2 arry 형태:  (2, 3)


- ndarray.ndim

In [25]:
print(array1.ndim)
print(array2.ndim)

1
2


### ndarray의 데이터 타입

In [27]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [30]:
### ndarray로 변경
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)  ## ndarray는 데이터값이 모두 같은 데이터 타입이어야 하므로 문자열로 변환됨

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)  ## ndarray는 데이터값이 모두 같은 데이터 타입이어야 하므로 float로 변환됨

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [33]:
## astype으로 변경 가능
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_float = array_int.astype('int32')
print(array_float, array_float.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

- 특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.zeros((3, 2), dtype = 'int32')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [36]:
np.ones((3, 2), dtype = 'int32')

array([[1, 1],
       [1, 1],
       [1, 1]])

### ndarray의 차원과 크기를 변경하는 reshape()

In [38]:
array1 = np.arange(10)

array2 = array1.reshape(2, 5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
array1 = np.arange(10)

array2 = array1.reshape(2, -1)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Indexing

In [43]:
### 단일값 추출
array1 = np.arange(start = 1, stop = 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
array1[2]

3

In [47]:
### 슬라이싱
array1 = np.arange(1, 11)
array3 = array1[0:3]
array3

array([1, 2, 3])

In [49]:
import numpy as np

array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
array2d[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [54]:
### 팬시 인덱싱
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
array3 = array2d[[0, 1], 2]
array3

array([3, 6])

In [ ]:
### 불린 인덱싱
array1d = np.arange

In [95]:
import numpy as np

array1d = np.arange(start = 1, stop = 10)
array3 = array1d[array1d > 5]
array3

array([6, 7, 8, 9])

In [97]:
boolean_indexes = array1d > 5
boolean_indexes

array([False, False, False, False, False,  True,  True,  True,  True])

In [98]:
array1d[boolean_indexes]

array([6, 7, 8, 9])

### 행렬의 정렬

- np.sort
- ndarray.sort()
- argsort()

- np.sort()...넘파이에서 sort()를 호출 : 원 행렬은 그대로 유지한채 원 행렬의 정렬된 행렬을 반환함
- ndarray.sort()...행렬 자체에서 sort() 호출 : 원 행렬 자체를 정렬한 형태로 변환하며 저장하지 않으면 반환값은 None임

In [99]:
org_array = np.array([3, 1, 9, 5])
org_array

array([3, 1, 9, 5])

In [101]:
sort_array1 = np.sort(org_array)
sort_array1

array([1, 3, 5, 9])

In [103]:
sort_array2 = org_array.sort()
sort_array2

In [106]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [107]:
array2d = np.array([[8, 12],
                   [7, 1]])
array2d

array([[ 8, 12],
       [ 7,  1]])

In [108]:
np.sort(array2d, axis = 0)

array([[ 7,  1],
       [ 8, 12]])

In [109]:
np.sort(array2d, axis = 1)

array([[ 8, 12],
       [ 1,  7]])

In [110]:
### 정렬된 행렬의 인덱스를 반환하기
org_array = np.array([3, 1, 9, 5])
np.argsort(org_array)

array([1, 0, 3, 2], dtype=int64)

In [111]:
np.argsort(org_array)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [113]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

indexes = np.argsort(score_array)
name_array[indexes]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [116]:
### 행렬 내적(행렬 곱)
A = np.array([[1, 2, 3],
            [4, 5, 6]])

B = np.array([[7, 8],
            [9, 10],
            [11, 12]])

dot_product = np.dot(A, B)
dot_product

array([[ 58,  64],
       [139, 154]])

In [117]:
A @ B

array([[ 58,  64],
       [139, 154]])

In [118]:
### 전치 행렬
A

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
transpose_mat = np.transpose(A)
transpose_mat

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Pandas

### pandas intro

In [121]:
import pydataset

mpg = pydataset.data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [122]:
mpg.shape

(234, 11)

In [123]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   fl            234 non-null    object 
 10  class         234 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [124]:
mpg.describe()

displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

In [125]:
mpg['cyl'].value_counts()

4    81
6    79
8    70
5     4
Name: cyl, dtype: int64

In [129]:
type(mpg['year'])

pandas.core.series.Series

In [38]:
df = mpg.iloc[:5, 2:5]
df

displ  year  cyl
1    1.8  1999    4
2    1.8  1999    4
3    2.0  2008    4
4    2.0  2008    4
5    2.8  1999    6

### dataframe과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

#### dataframe으로 변환하기

In [135]:
import numpy as np
import pandas as pd

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)

df_list1 = pd.DataFrame(list1, columns = col_name1)
df_list1

col1
0     1
1     2
2     3

In [136]:
df_array1 = pd.DataFrame(array1, columns = col_name1)
df_array1

col1
0     1
1     2
2     3

In [137]:
### 2차원
col_name2 = ['col1', 'col2', 'col3']

list2 = [[1, 2, 3],
        [11, 12, 13]]
array2 = np.array(list2)

df_list2 = pd.DataFrame(list2, columns = col_name2)
df_list2

col1  col2  col3
0     1     2     3
1    11    12    13

In [139]:
df_array2 = pd.DataFrame(array2, columns = col_name2)
df_array2

col1  col2  col3
0     1     2     3
1    11    12    13

In [141]:
### dictionary
dict = {'col1' :[1, 11], 'col2' : [2, 22], 'col3' : [3, 33]}
df_dict = pd.DataFrame(dict)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

#### dataframe을 변환하기

In [13]:
# df -> array
df.values

array([[1.800e+00, 1.999e+03, 4.000e+00],
       [1.800e+00, 1.999e+03, 4.000e+00],
       [2.000e+00, 2.008e+03, 4.000e+00],
       [2.000e+00, 2.008e+03, 4.000e+00],
       [2.800e+00, 1.999e+03, 6.000e+00]])

In [14]:
# df -> dictionary
df.to_dict

<bound method DataFrame.to_dict of    displ  year  cyl
1    1.8  1999    4
2    1.8  1999    4
3    2.0  2008    4
4    2.0  2008    4
5    2.8  1999    6>

In [20]:
# df -> list(1)
df.values.tolist()

[[1.8, 1999.0, 4.0],
 [1.8, 1999.0, 4.0],
 [2.0, 2008.0, 4.0],
 [2.0, 2008.0, 4.0],
 [2.8, 1999.0, 6.0]]

In [21]:
# df -> list(2)
df['displ'].tolist()

[1.8, 1.8, 2.0, 2.0, 2.8]

#### df를 하나의 리스트로 만들어주세요.

In [42]:
[y for x in df.values.tolist() for y in x ]

[1.8,
 1999.0,
 4.0,
 1.8,
 1999.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.8,
 1999.0,
 6.0]

In [36]:
import numpy as np

df=np.array(df)
df.flatten() 

array([1.800e+00, 1.999e+03, 4.000e+00, 1.800e+00, 1.999e+03, 4.000e+00,
       2.000e+00, 2.008e+03, 4.000e+00, 2.000e+00, 2.008e+03, 4.000e+00,
       2.800e+00, 1.999e+03, 6.000e+00])

In [39]:
dfli = df.values.tolist()
li = []
for i in dfli:
    for j in i:
        li.append(j) 

In [40]:
df.values.flatten().tolist() 

[1.8,
 1999.0,
 4.0,
 1.8,
 1999.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.8,
 1999.0,
 6.0]

In [41]:
df.values.reshape(-1).tolist() 

[1.8,
 1999.0,
 4.0,
 1.8,
 1999.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.0,
 2008.0,
 4.0,
 2.8,
 1999.0,
 6.0]

### DataFrame 칼럼 데이터 세트 생성과 수정

In [143]:
mpg['mpg0'] = 0
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact   
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact   
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact   

   mpg0  
1     0  
2     0  
3     0  
4     0  
5     0

In [147]:
## axis = 0은 로우 방향 |
## axis = 1은 칼럼 방향 --

mpg = mpg.drop(['mpg0'], axis = 1)
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [148]:
#### index 객체
mpg.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            225, 226, 227, 228, 229, 230, 231, 232, 233, 234],
           dtype='int64', length=234)

In [151]:
mpg1 = mpg.groupby(['year', 'manufacturer']).mean()
mpg1

displ       cyl        cty        hwy
year manufacturer                                          
1999 audi          2.355556  5.111111  17.111111  26.111111
     chevrolet     4.971429  7.142857  15.142857  21.571429
     dodge         4.318750  6.750000  13.375000  18.437500
     ford          4.453333  7.066667  13.933333  18.600000
     honda         1.600000  4.000000  24.800000  31.600000
     hyundai       2.300000  4.666667  18.333333  26.666667
     jeep          4.350000  7.000000  14.500000  18.500000
     land rover    4.300000  8.000000  11.000000  15.000000
     lincoln       5.400000  8.000000  11.000000  16.500000
     mercury       4.500000  7.000000  13.500000  17.000000
     nissan        2.900000  5.333333  17.666667  23.500000
     pontiac       3.566667  6.000000  17.000000  26.333333
     subaru        2.400000  4.000000  19.000000  25.500000
     toyota        2.765000  5.000000  18.150000  24.050000
     volkswagen    2.206250  4.625000  21.250000  29.687500
2008 audi          2.733333  5.333333  18.111111  26.777778
     chevrolet     5.116667  7.333333  14.916667  22.083333
     dodge         4.423810  7.333333  12.952381  17.571429
     ford          4.660000  7.400000  14.100000  20.500000
     honda         1.850000  4.000000  24.000000  33.750000
     hyundai       2.525000  5.000000  18.875000  27.000000
     jeep          4.650000  7.333333  13.166667  17.333333
     land rover    4.300000  8.000000  12.000000  18.000000
     lincoln       5.400000  8.000000  12.000000  18.000000
     mercury       4.300000  7.000000  13.000000  19.000000
     nissan        3.585714  5.714286  18.428571  25.571429
     pontiac       4.550000  7.000000  17.000000  26.500000
     subaru        2.500000  4.000000  19.500000  25.625000
     toyota        3.221429  5.285714  19.071429  26.142857
     volkswagen    2.327273  4.545455  20.454545  28.545455

In [155]:
mpg1.reset_index().head()

year manufacturer     displ       cyl        cty        hwy
0  1999         audi  2.355556  5.111111  17.111111  26.111111
1  1999    chevrolet  4.971429  7.142857  15.142857  21.571429
2  1999        dodge  4.318750  6.750000  13.375000  18.437500
3  1999         ford  4.453333  7.066667  13.933333  18.600000
4  1999        honda  1.600000  4.000000  24.800000  31.600000

In [157]:
## drop = True로 설정하면 기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제됨
mpg1.reset_index(drop = True).head()

displ       cyl        cty        hwy
0  2.355556  5.111111  17.111111  26.111111
1  4.971429  7.142857  15.142857  21.571429
2  4.318750  6.750000  13.375000  18.437500
3  4.453333  7.066667  13.933333  18.600000
4  1.600000  4.000000  24.800000  31.600000

### 데이터 셀렉션 및 필터링

In [158]:
mpg[0:4]

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact

In [162]:
mpg[mpg['model'] == 'a4']

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact
6         audi    a4    2.8  1999    6  manual(m5)   f   18   26  p  compact
7         audi    a4    3.1  2008    6    auto(av)   f   18   27  p  compact

In [164]:
data = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
       'Year' : [2011, 2016, 2015, 2015],
       'Gender' : ['Male', 'Female', 'Male', 'Male']}
data

{'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
 'Year': [2011, 2016, 2015, 2015],
 'Gender': ['Male', 'Female', 'Male', 'Male']}

In [165]:
data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [166]:
data_df.iloc[0, 0]

'Chulmin'

In [168]:
data_df.iloc[0:2, 0:2]

Name  Year
one   Chulmin  2011
two  Eunkyung  2016

In [169]:
data_df.loc['one', 'Name']

'Chulmin'

In [170]:
data_df.loc['one':'three', 'Year':'Gender']

Year  Gender
one    2011    Male
two    2016  Female
three  2015    Male

In [171]:
data_df.loc[data_df.Year >= 2014]

Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [173]:
## and : &
## or : |
## Not : ~

data_df[(data_df.Year >= 2014) & (data_df.Gender == 'Male')]

Name  Year Gender
three  Jinwoong  2015   Male
four    Soobeom  2015   Male

### 정렬, Aggregation, Groupby

In [174]:
mpg.sort_values(by = ['year'])

manufacturer               model  displ  year  cyl       trans drv  cty  \
1           audi                  a4    1.8  1999    4    auto(l5)   f   18   
126         jeep  grand cherokee 4wd    4.7  1999    8    auto(l4)   4   14   
131   land rover         range rover    4.0  1999    8    auto(l4)   4   11   
134   land rover         range rover    4.6  1999    8    auto(l4)   4   11   
135      lincoln       navigator 2wd    5.4  1999    8    auto(l4)   r   11   
..           ...                 ...    ...   ...  ...         ...  ..  ...   
129         jeep  grand cherokee 4wd    5.7  2008    8    auto(l5)   4   13   
128         jeep  grand cherokee 4wd    4.7  2008    8    auto(l5)   4   14   
127         jeep  grand cherokee 4wd    4.7  2008    8    auto(l5)   4    9   
145       nissan              altima    2.5  2008    4  manual(m6)   f   23   
234   volkswagen              passat    3.6  2008    6    auto(s6)   f   17   

     hwy fl    class  
1     29  p  compact  
126   17  r      suv  
131   15  p      suv  
134   15  p      suv  
135   17  r      suv  
..   ... ..      ...  
129   18  r      suv  
128   19  r      suv  
127   12  e      suv  
145   32  r  midsize  
234   26  p  midsize  

[234 rows x 11 columns]

In [175]:
mpg[['cty', 'hwy']].mean()

cty    16.858974
hwy    23.440171
dtype: float64

In [177]:
mpg.groupby('model').mean()

displ         year       cyl        cty        hwy
model                                                                        
4runner 4wd             3.483333  2002.000000  5.666667  15.166667  18.833333
a4                      2.328571  2002.857143  4.857143  18.857143  28.285714
a4 quattro              2.425000  2003.500000  5.000000  17.125000  25.750000
a6 quattro              3.366667  2005.000000  6.666667  16.000000  24.000000
altima                  2.800000  2005.000000  4.666667  20.666667  28.666667
c1500 suburban 2wd      5.520000  2006.200000  8.000000  12.800000  17.800000
camry                   2.671429  2002.857143  4.857143  19.857143  28.285714
camry solara            2.642857  2002.857143  4.857143  19.857143  28.142857
caravan 2wd             3.390909  2003.090909  5.818182  15.818182  22.363636
civic                   1.711111  2003.000000  4.000000  24.444444  32.555556
corolla                 1.800000  2002.600000  4.000000  25.600000  34.000000
corvette                6.160000  2004.400000  8.000000  15.400000  24.800000
dakota pickup 4wd       4.411111  2004.000000  7.111111  12.777778  17.000000
durango 4wd             4.971429  2004.142857  7.714286  11.857143  16.000000
expedition 2wd          5.133333  2002.000000  8.000000  11.333333  17.333333
explorer 4wd            4.266667  2002.000000  6.666667  13.666667  18.000000
f150 pickup 4wd         4.714286  2001.571429  7.428571  13.000000  16.428571
forester awd            2.500000  2005.000000  4.000000  18.833333  25.000000
grand cherokee 4wd      4.575000  2005.750000  7.250000  13.500000  17.625000
grand prix              3.960000  2002.600000  6.400000  17.000000  26.400000
gti                     2.160000  2002.600000  4.400000  20.000000  27.400000
impreza awd             2.425000  2003.500000  4.000000  19.625000  26.000000
jetta                   2.277778  2003.000000  4.666667  21.222222  29.111111
k1500 tahoe 4wd         5.700000  2003.500000  8.000000  12.500000  16.250000
land cruiser wagon 4wd  5.200000  2003.500000  8.000000  12.000000  16.500000
malibu                  3.000000  2004.400000  5.200000  18.800000  27.600000
maxima                  3.166667  2002.000000  6.000000  18.666667  25.333333
mountaineer 4wd         4.400000  2003.500000  7.000000  13.250000  18.000000
mustang                 4.377778  2004.000000  7.111111  15.888889  23.222222
navigator 2wd           5.400000  2002.000000  8.000000  11.333333  17.000000
new beetle              2.133333  2002.000000  4.333333  24.000000  32.833333
passat                  2.400000  2002.857143  4.857143  18.571429  27.571429
pathfinder 4wd          4.050000  2003.500000  6.500000  13.750000  18.000000
ram 1500 pickup 4wd     5.020000  2005.300000  8.000000  11.400000  15.300000
range rover             4.300000  2003.500000  8.000000  11.500000  16.500000
sonata                  2.557143  2002.857143  4.857143  19.000000  27.714286
tiburon                 2.300000  2005.428571  4.857143  18.285714  26.000000
toyota tacoma 4wd       3.271429  2002.857143  5.142857  15.571429  19.428571

In [178]:
mpg.groupby('model').agg(['max', 'min'])

manufacturer             displ       year       cyl  \
                                max         min   max  min   max   min max   
model                                                                        
4runner 4wd                  toyota      toyota   4.7  2.7  2008  1999   8   
a4                             audi        audi   3.1  1.8  2008  1999   6   
a4 quattro                     audi        audi   3.1  1.8  2008  1999   6   
a6 quattro                     audi        audi   4.2  2.8  2008  1999   8   
altima                       nissan      nissan   3.5  2.4  2008  1999   6   
c1500 suburban 2wd        chevrolet   chevrolet   6.0  5.3  2008  1999   8   
camry                        toyota      toyota   3.5  2.2  2008  1999   6   
camry solara                 toyota      toyota   3.3  2.2  2008  1999   6   
caravan 2wd                   dodge       dodge   4.0  2.4  2008  1999   6   
civic                         honda       honda   2.0  1.6  2008  1999   4   
corolla                      toyota      toyota   1.8  1.8  2008  1999   4   
corvette                  chevrolet   chevrolet   7.0  5.7  2008  1999   8   
dakota pickup 4wd             dodge       dodge   5.2  3.7  2008  1999   8   
durango 4wd                   dodge       dodge   5.9  3.9  2008  1999   8   
expedition 2wd                 ford        ford   5.4  4.6  2008  1999   8   
explorer 4wd                   ford        ford   5.0  4.0  2008  1999   8   
f150 pickup 4wd                ford        ford   5.4  4.2  2008  1999   8   
forester awd                 subaru      subaru   2.5  2.5  2008  1999   4   
grand cherokee 4wd             jeep        jeep   6.1  3.0  2008  1999   8   
grand prix                  pontiac     pontiac   5.3  3.1  2008  1999   8   
gti                      volkswagen  volkswagen   2.8  2.0  2008  1999   6   
impreza awd                  subaru      subaru   2.5  2.2  2008  1999   4   
jetta                    volkswagen  volkswagen   2.8  1.9  2008  1999   6   
k1500 tahoe 4wd           chevrolet   chevrolet   6.5  5.3  2008  1999   8   
land cruiser wagon 4wd       toyota      toyota   5.7  4.7  2008  1999   8   
malibu                    chevrolet   chevrolet   3.6  2.4  2008  1999   6   
maxima                       nissan      nissan   3.5  3.0  2008  1999   6   
mountaineer 4wd             mercury     mercury   5.0  4.0  2008  1999   8   
mustang                        ford        ford   5.4  3.8  2008  1999   8   
navigator 2wd               lincoln     lincoln   5.4  5.4  2008  1999   8   
new beetle               volkswagen  volkswagen   2.5  1.9  2008  1999   5   
passat                   volkswagen  volkswagen   3.6  1.8  2008  1999   6   
pathfinder 4wd               nissan      nissan   5.6  3.3  2008  1999   8   
ram 1500 pickup 4wd           dodge       dodge   5.9  4.7  2008  1999   8   
range rover              land rover  land rover   4.6  4.0  2008  1999   8   
sonata                      hyundai     hyundai   3.3  2.4  2008  1999   6   
tiburon                     hyundai     hyundai   2.7  2.0  2008  1999   6   
toyota tacoma 4wd            toyota      toyota   4.0  2.7  2008  1999   6   

                                 trans           drv     cty     hwy      fl  \
                       min         max       min max min max min max min max   
model                                                                          
4runner 4wd              4  manual(m5)  auto(l4)   4   4  16  14  20  17   r   
a4                       4  manual(m6)  auto(av)   f   f  21  16  31  26   p   
a4 quattro               4  manual(m6)  auto(l5)   4   4  20  15  28  25   p   
a6 quattro               6    auto(s6)  auto(l5)   4   4  17  15  25  23   p   
altima                   4  manual(m6)  auto(av)   f   f  23  19  32  26   r   
c1500 suburban 2wd       8    auto(l4)  auto(l4)   r   r  14  11  20  15   r   
camry                    4  manual(m5)  auto(l4)   f   f  21  18  31  26   r   
camry solara            

### 결손 데이터 처리하기

In [183]:
import pydataset

titanic = pydataset.data('titanic')
titanic.head()

class     age  sex survived
1  1st class  adults  man      yes
2  1st class  adults  man      yes
3  1st class  adults  man      yes
4  1st class  adults  man      yes
5  1st class  adults  man      yes

In [186]:
titanic['sex'] = titanic['sex'].fillna('S')

In [187]:
titanic.isna().sum()

class       0
age         0
sex         0
survived    0
dtype: int64

### apply lambda 식으로 데이터 가공

In [189]:
lambda_square = lambda x: x * 2

print('3의 제곱은 ', lambda_square(3))

3의 제곱은  6


In [191]:
mpg['hwy'] = mpg['hwy'].apply(lambda x: 'high' if x >= 30 else 'average')
mpg

manufacturer   model  displ  year  cyl       trans drv  cty      hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18  average  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21  average  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20     high  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21     high  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16  average  p   
..           ...     ...    ...   ...  ...         ...  ..  ...      ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19  average  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21  average  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16  average  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18  average  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17  average  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[234 rows x 11 columns]

### Numpy와 Pandas 자세한 내용 colab 참고

# 사이킷런(85p)

In [192]:
pip install -U scikit-learn

  Using cached scikit_learn-1.1.2-cp310-cp310-win_amd64.whl (7.4 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\~-learn\\.libs\\vcomp140.dll'
Consider using the `--user` option or check the permissions.



In [197]:
import sklearn

In [198]:
sklearn.__version__

'1.0.2'

In [199]:
pip list | findstr sk

Flask                2.2.2
Flask-Compress       1.13
Note: you may need to restart the kernel to use updated packages.


## 1. 붓꽃 품종 예측하기

- 분류는 대표적인 지도학습 방법의 하나임
- 지도학습은 학습을 위한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측함

- 하이퍼 파라미터란 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터들을 통칭함

In [200]:
from sklearn.datasets import load_iris

In [201]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [202]:
iris = load_iris()            # 붖꽃 데이터 세트 로딩
iris    ### array 형태로 되어있음

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [65]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [66]:
type(iris)

sklearn.utils.Bunch

In [67]:
iris['data'] 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [68]:
# iris['data']는 아래와 유사함
d = {'apple' : '사과'}
d['apple']

'사과'

In [69]:
iris_data = iris['data']
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [70]:
iris_label = iris['target']
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [71]:
train_test_split(iris_label)    # 2조각으로 나눔(5:5가 아닌 75%/25%으로 쪼갬)

[array([0, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2,
        2, 2, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0,
        1, 1, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 2, 1,
        0, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1,
        2, 0, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 1, 1,
        2, 0]),
 array([1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 2, 1, 1,
        0, 1, 0, 1, 1, 2, 2, 1, 1, 0, 0, 1, 2, 2, 2, 1])]

In [208]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)  
# 2개를 2조각으로 나누므로 총 4조각 생성

# iris_data : 피처 데이터 세트
# iris_label : 레이블 데이터 세트
# test_size : 전체 데이터 세트 중 테스트 데이터 세트의 비율
# random_state : 호출할 때마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값

# tran_test_split()는 호출 시 무작위로 데이터를 분리하므로 random_state를 지정하지 않으면 수행할 때마다 다른 학습/테스트 용 데이터를 만들 수 있음
# random_state는 random값을 만드는 seed와 같은 의미

In [209]:
X_train # 학습용 피처 데이터 세트

array([[5.1, 3.5, 1.4, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5. , 3.3, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3. , 5. , 1.7],
       [5.5, 3.5, 1.3, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [5. , 2. , 3.5, 1. ],
       [7.9, 3.8, 6.4, 2. ],
       [4.6, 3.4, 1.4, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 3. , 5.8, 2.2],
       [5.1, 2.5, 3. , 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.1, 3.7, 1.5, 0.4],
       [5. , 3.4, 1.6, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3

In [210]:
X_test # 테스트용 피처 데이터 세트

array([[6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [6. , 2.2, 5. , 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.9, 5.6, 1.8],
       [5.6, 3. , 4.5, 1.5],
       [6.5, 3.2, 5.1, 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.5, 3.9, 1.1],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [6. , 3.4, 4.5, 1.6]])

In [211]:
y_train # 학습용 레이블 데이터 세트

array([0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2,
       2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2,
       1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0,
       2, 1, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 0, 1, 1, 1, 0, 1, 1, 1])

In [212]:
y_test # 테스트용 레이블 데이터 세트

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [213]:
dt_clf = DecisionTreeClassifier()  # DecisionTreeClassifier 객체 생성

In [78]:
dt_clf.fit(X_train, y_train)  ## Train시키는 것(fitting, 적합, 학습한다, 훈련한다)

DecisionTreeClassifier()

In [79]:
X_train.shape

(112, 4)

- data의 개수는 112개

In [80]:
y_train.shape

(112,)

- X_train 의 4가지 정보로 y_train의 값을 예측하므로 data의 개수는 같아야함

In [81]:
y_pred = dt_clf.predict(X_test)  ### train할 때 4개의 정보로 값 하나를 도출해냈으므로 4개의 정보를 줘야 함
y_pred

array([0, 0, 2, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2])

In [82]:
X_test.shape

(38, 4)

In [83]:
y_pred == y_test   ### numpy가 element wise하게 비교함

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False])

In [84]:
sum(y_pred == y_test ) ### True는 1임

36

In [85]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [86]:
from sklearn.metrics import accuracy_score

In [87]:
accuracy_score(y_test, y_pred)  ## 두 요소를 비교하고 예측 정확도를 계산해줌

0.9473684210526315

In [214]:
#####SUMMARY#####

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

iris = load_iris()    # 붖꽃 데이터 세트 로딩

iris_data = iris['data']
iris_label = iris['target']

X_train, X_test, y_train, y_test = train_test_split(iris_data, 
                                                    iris_label)  ## train용, test용 데이터 나누기

dt_clf = DecisionTreeClassifier()

dt_clf.fit(X_train, y_train)   ## Train시키는 것(fitting, 적합, 학습한다, 훈련한다)

y_pred = dt_clf.predict(X_test)  ## train기반으로 predict하기(예측 수행)

acc_score = accuracy_score(y_test, y_pred)  ## 두 요소를 비교하고 예측 정확도를 계산해줌
acc_score

0.9473684210526315

## 사이킷런의 기반 프레임워크 익히기

---사이킷런 메서드---
- fit() : ML 모델 학습
- predict() : 학습된 모델 예측

- fit()과 predict()는 분류(Classification)와 회귀(Regression)의 다양한 알고리즘을 구현했으며 간단하게 학습과 예측 결과 반환함
- Classifier : 분류 알고리즘을 구현한 클래스
- Regressor : 회귀 알고리즘을 구현한 클래스
- Estimator 클래스 = Classifier + Regressor

---사이킷런의 주요 모듈---
- 92-92p 참조


---일반적인 머신러닝 모델 구축 주요 프로세스---
- 피처 처리(feature processing) : 피처의 가공, 변경, 추출을 수행
- ML 알고리즘 학습/예측 수행
- 모델 평가

### 내장된 예제 데이터 세트
- 94-95p 참고

In [220]:
from sklearn.datasets import load_boston

In [222]:
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [223]:
keys = boston.keys()
keys

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

- 데이터 키는 피처들의 데이터 값을 가리킴
- 데이터 세트가 딕셔너리 형태이기 때문에 피처 데이터를 추출하기 위해서는 데이터 세트, data를 이용하면 됨

In [228]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [229]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [230]:
len(iris.feature_names)

4

In [231]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [232]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [234]:
iris.data.shape

(150, 4)

In [235]:
iris.target.shape

(150,)

### Model Selection 모듈 소개

#### train-test-split()

In [238]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

pred = dt_clf.predict(train_data)
accuracy_score(train_label, pred)

1.0

- 위의 예측 결과가 100%인 이유는 이미 학습한 학습 데이터 세트를 기반으로 예측했기 때문임
- 따라서 예측을 수행하는 데이터 세트는 학습을 수행한 학습용 데이터 세트가 아닌 전용의 테스트 데이터 세트여야 함
- train_test_split()를 통해 원본 데이터 세트에서 학습 및 테스트 데이터 세트를 쉽게 분리할 수 있음

---train_test_split() 파라미터---
- test_size : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인가를 결정
- train_size : 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것인가를 결정(디폴트는 25%/0.25)
- shuffle : 데이터를 분리하기 전에 데이터를 미리 섞을 지 결정(데이터를 분산시켜 좀 더 효율적인 학습 및 데이터 세트를 만드는 데 사용함)
- random_state : 호출할 때마다 동일한 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값

random_state
: 숫자가 random해보여도 컴퓨터는 어떤 알고리즘을 통해서 랜덤 숫자를 부여함 시작하는 패턴을 결정하는 것이므로 아무 숫자를 줘도 상관없음

- train_test_split()의 반환값은 튜플 형태임

In [239]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [240]:
dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

In [241]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

In [244]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0,
       1])

In [245]:
accuracy_score(y_test, pred)

0.9555555555555556

- 학습을 위한 데이터 양을 일정 수준 이상으로 보장하는 것 중요
- 학습된 모델에 대해 다양한 데이터를 기반으로 예측 성능을 평가해보는 것도 중요

## 데이터 전처리

- Garbage in Garbage out
- 결손값(NaN, Null은 허용되지 않음)
- 고정된 다른 값으로 변환 필요함

- 사이킷런의 머신러닝 알고리즘은 문자열 값을 입력값으로 허용하지 않음
- 문자열을 인코딩 해 숫자형으로 변환 필요

### 데이터 인코딩
- 레이블 인코딩(label encoding) :  카테고리 피처를 코드형 숫자 값으로 변환
- 원-핫 인코딩(one hot encoding)

In [89]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [92]:
encoder.fit_transform(['TV', '냉장고', '전자레인지'])  ## 숫자로 바꾸어줌!

array([0, 1, 2], dtype=int64)