# 복습 문제

In [1]:
## ML 알고리즘에 사용할 제이터는 결손값이 있어서는 안되지만 숫자열과 문자열 모두 가능하다

# X
# 문자열 안됨

In [2]:
## 지도학습은 학습을 위한 다양한 피처(Y)와 분류 결정값인 레이블(X) 데이터로 모델을 학습한다

# X
# X, Y 바꿔야 함

In [3]:
## 분류는 답이 정해져있고 군집화는 답이 정해져있지 않다

# O

In [4]:
# 사이킷런에서 분류 알고리즘을 구현하는 크래스 - Classifier
# 사이킷런에서 회귀 알고리즘을 구현하는 클래스 - Regressor
# 위 두 클래스를 합쳐서 지도학습의 모든 알고리즘을 구현한 클래스 - Estimator

In [5]:
## 사이킷런의 머신러닝 알고리즘은 문자열 값을 입력값으로 허용되지 않지만, NaN, Null 값은 허용된다.

# X
# 결손값 안됨

In [19]:
## encoding

from sklearn.preprocessing import LabelEncoder
import numpy as np

In [10]:
arr = np.array(['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']*10) 
arr

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터',
       '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기',
       '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',
       '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV',
       '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [14]:
encoder = LabelEncoder()

labels = encoder.fit_transform(arr)
labels

array([0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3,
       2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5,
       3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1,
       4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [61]:
## dataframe으로 만들기

from sklearn.datasets import load_iris
iris = load_iris()

In [62]:
iris_data = iris['data']
iris_label = iris['target']

In [63]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [64]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [65]:
import pandas as pd

iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [66]:
iris_df['label'] = iris_label   ## iris_label = iris['target']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [35]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [37]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [49]:
## label의 숫자를 target_names 문자로 바꾸기

iris_df['label'] = iris_df['label'].map({0 : 'setosa', 1 : 'versicolor', 2 : 'virginica'})
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         label  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [67]:
label_mapping = {0 : 'setosa', 1 : 'versicolor', 2 : 'virginica'}
iris_df['label'] = iris_df['label'].map(label_mapping)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         label  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [72]:
## df를 리스트로 변환하기

di = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df_di = pd.DataFrame(di) 
df_di

col1  col2  col3
0     1     2     3
1    11    22    33

In [77]:
df_di.values.tolist()

[[1, 2, 3], [11, 22, 33]]

In [82]:
df_di.values.flatten().tolist()

[1, 2, 3, 11, 22, 33]

In [84]:
[y for x in df_di.values.tolist() for y in x ] 

[1, 2, 3, 11, 22, 33]

In [85]:
## 행렬 정렬은 np.sort()와 같이 sort()를 호출하는 방식과 
## ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있음
## 두 방식의 차이는?

# np.sort()는 기존 행렬은 유지한 채로 정렬 값을 반환, 
# ndarray.sort()는 기존 행렬을 변경해주고 반환값 None 

In [87]:
## 데이터를 학습/테스트 데이터로 분리하는 함수는?

# from sklearn.model_selection import train_test_split
# train_test_split() 

In [88]:
## 전체 흐름 쭉 쓰기

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [89]:
dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

In [90]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

In [91]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0,
       1])

In [92]:
accuracy_score(y_test, pred)

0.9555555555555556

# 수업

## One-Hot Encoding 118p

- 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식임

- 행 형태로 돼 있는 피처의 고유값을 열 형태로 차원을 변환한 뒤, 고유값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시함

- 사이킷런에서 OneHotEncoder 클래스로 변환 가능함
- 입력값으로 2차원 데이터 필요
- 변환한 값을 다시 toarray() 메서드를 이용해 밀집 행렬으로 변환해야 함

In [108]:
from sklearn.preprocessing import OneHotEncoder

items = ['TV', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서기', '믹서기']
items = np.array(items).reshape(-1, 1)   ## 형태가 하나의 열이어야만 함

encoder = OneHotEncoder()

In [109]:
encoder.fit(items)   ## 7개이지만 5개의 요소들이 있으므로 5개로 틀을 잡아줌

OneHotEncoder()

In [110]:
labels = encoder.transform(items)

In [111]:
labels.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [112]:
labels.shape

(7, 5)

In [113]:
### pandas
items = ['TV', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서기', '믹서기']

pd.get_dummies(items)

TV  믹서기  선풍기  전자레인지  컴퓨터
0   1    0    0      0    0
1   0    0    0      1    0
2   0    0    0      0    1
3   0    0    1      0    0
4   0    0    1      0    0
5   0    1    0      0    0
6   0    1    0      0    0

- get_dummies를 이용하면 숫자형 값으로 변환 없이도 바로 변환 가능함

## 교차검증(Cross Validation) 100p

과적합
- 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어지는 것

교차검증
- 데이퍼 편중을 막기 위해서 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평과를 수행하는 것

### K 폴드 교차 검증

- 먼저 K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행

In [117]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

In [118]:
iris = load_iris()                   # 파일부르기

iris_data = iris.data  # data(정보)와 target(매치대상) 저장
iris_label= iris.target


dt_clf=DecisionTreeClassifier()      # 의사결정 트리 
kfold = KFold(n_splits = 5)
cv_accuracy = []

In [120]:
n_iter = 0

for train_index, test_index in kfold.split(iris_data):
    print(train_index)
    print(test_index)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [122]:
iris = load_iris()                   # 파일부르기

iris_data = iris.data
                # data(정보)와 target(매치대상) 저장
iris_label= iris.target


dt_clf = DecisionTreeClassifier()      # 의사결정 트리 
kfold = KFold(n_splits=5)

cv_accuracy = []

# KFold객체의 split( ) 호출하면 폴드 별 학습용, 검증용 테스트의 인덱스를 반환한다. 이거 중요함.  
for train_index, test_index  in kfold.split(iris_data): 
    
    # print(train_index, test_index)
    # print("---"*10)
    # kfold.split( )으로 반환된 인덱스를 이용하여 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]

    
    dt_clf.fit(X_train , y_train)    
    pred = dt_clf.predict(X_test)
    
   
    accuracy = accuracy_score(y_test,pred)   
    cv_accuracy.append(accuracy)
 
    print("개별 검증 정확도: ", cv_accuracy)
    
print('평균 검증 정확도:', np.mean(cv_accuracy)) 


개별 검증 정확도:  [1.0]
개별 검증 정확도:  [1.0, 1.0]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667, 0.9333333333333333]
개별 검증 정확도:  [1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]
평균 검증 정확도: 0.9066666666666666


- 위 split는 제대로 쪼개지지 않음
- 위와 같이 split하려면 전체적으로 분산이 잘 되어있어야만 함
- 앞에는 0만 있고 뒤에 2가 5개 있으면 Train데이터에는 2가 전혀 들어가지 않음
- 0이 100개면 train에는 70개 test에는 30개가 들어가야 함
- 1이 10개이면 train에는 7개 test에는 3개가 들어가야 함

- 계층, 층화
- stratified

### Stratified K 폴드

- 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식
- 불균형한 분포도를 가진 레이블 데이터 집합은 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한 쪽으로 치우치는 것을 말함

- 원본 데이터와 유사한 레이블 값의 학습/테스트 세트에도 유지하는 것이 매우 중요함

In [123]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

In [124]:
iris = load_iris()

features = X = iris_data = iris.data
labels = y = iris_label = iris.target

In [125]:
dt_clf = DecisionTreeClassifier()

In [127]:
s_kfold = StratifiedKFold(n_splits = 3)

cv_accuracy = []

In [137]:
for train_index, test_index in s_kfold.split(features, labels):
    # print(train_index)
    # print()
    # print(test_index)
    # print('------------------------------------------------------------')
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    acc = accuracy_score(y_test, pred)
    cv_accuracy.append(acc)
    
    print('개별 정확도 : ', acc)
    
print('정확도 모음 : ', cv_accuracy)

개별 정확도 :  0.98
개별 정확도 :  0.92
개별 정확도 :  1.0
정확도 모음 :  [0.98, 0.92, 1.0, 0.98, 0.92, 1.0]


In [139]:
np.mean(cv_accuracy).round(4)

0.9667

### cross_val_score()

In [140]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

In [141]:
data = features = X = iris_data = iris.data
label = labels = y = iris_label = iris.target

dt_clf = DecisionTreeClassifier()

In [144]:
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv = 3)
scores

array([0.98, 0.92, 0.98])

In [147]:
np.mean(scores)

0.96

### GridSearch

In [148]:
from sklearn.model_selection import GridSearchCV, train_test_split

In [153]:
iris = load_iris()

features = X = iris_data = iris.data
labels = y = iris_label = iris.target

X_train, X_test, y_train, y_test = train_test_split(features, labels, 
                                                    test_size = 0.3, random_state = 121)

dt_clf = DecisionTreeClassifier()

grid_parameters = {'max_depth' : [1, 2, 3],
                   'min_samples_split' : [2, 3]} 

grid_tree = GridSearchCV(dt_clf, param_grid = grid_parameters, cv = 3, refit = True)
grid_tree

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [155]:
grid_tree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [157]:
grid_tree.cv_results_

{'mean_fit_time': array([0.00100676, 0.        , 0.        , 0.00066479, 0.00066479,
        0.00099738]),
 'std_fit_time': array([8.14500454e-04, 0.00000000e+00, 0.00000000e+00, 4.70078102e-04,
        4.70643522e-04, 6.25769923e-07]),
 'mean_score_time': array([0.00066471, 0.0006659 , 0.        , 0.        , 0.        ,
        0.        ]),
 'std_score_time': array([0.00047002, 0.00047087, 0.        , 0.        , 0.        ,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'ma

In [160]:
pd.DataFrame(grid_tree.cv_results_).iloc[:, 5:]

param_min_samples_split                                    params  \
0                       2  {'max_depth': 1, 'min_samples_split': 2}   
1                       3  {'max_depth': 1, 'min_samples_split': 3}   
2                       2  {'max_depth': 2, 'min_samples_split': 2}   
3                       3  {'max_depth': 2, 'min_samples_split': 3}   
4                       2  {'max_depth': 3, 'min_samples_split': 2}   
5                       3  {'max_depth': 3, 'min_samples_split': 3}   

   split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
0           0.657143           0.657143           0.657143         0.657143   
1           0.657143           0.657143           0.657143         0.657143   
2           0.942857           0.914286           0.942857         0.933333   
3           0.942857           0.914286           0.942857         0.933333   
4           0.971429           0.914286           0.942857         0.942857   
5           0.971429           0.914286           0.942857         0.942857   

   std_test_score  rank_test_score  
0        0.000000                5  
1        0.000000                5  
2        0.013469                3  
3        0.013469                3  
4        0.023328                1  
5        0.023328                1

In [158]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [161]:
grid_tree.best_score_

0.9428571428571427

- GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음

In [164]:
pred = grid_tree.predict(X_test)
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0,
       1])

In [165]:
accuracy_score(y_test, pred)

0.9555555555555556

### MinMaxScaler

정규화(Normalization)
- scale을 조정할 때 정규화는 보통 최솟값이 0, 최댓값이 1이 되도록 scale을 조정
- 함수를 직접 작성하거나, MinMax Scaler에 의해 Scaling 함

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(iris_scaled.max(axis = 0))
print(iris_scaled.min(axis = 0))

In [179]:
iris = load_iris()
iris = iris.data
iris_df = pd.DataFrame(iris)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [180]:
iris_df.max()

0    7.9
1    4.4
2    6.9
3    2.5
dtype: float64

In [181]:
iris_df.min()

0    4.3
1    2.0
2    1.0
3    0.1
dtype: float64

In [182]:
def min_max(x):
    return ( x - x.min() ) / ( x.max() - x.min() )

In [183]:
iris_df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [184]:
iris_df.apply(min_max)

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [185]:
iris_df.apply(min_max).max()

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [188]:
iris_df.apply(lambda x: (x - x.min()) / (x.max() - x.min()))

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [202]:
## 방법 2
from sklearn.preprocessing import MinMaxScaler

In [191]:
scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled


## iris_scaled  = scaler.fit_transform(iris_df)

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

### 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

- Scaler 객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면 테스트 데이터 세트로는 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform() 변환을 적용해야 함

In [192]:
X_train, X_test = train_test_split(iris_data)

- X_train과 X_test를 각각 따로 정규화를 해도 괜찮을까?

- fit()은 데이터 변환을 위한 기준 정보 설정을 적용

- transform()은 이렇게 설정된 정보를 이용해 데이터를 변환함

- 위와 같이 하면 X_train과 X_test의 최댓값과 최솟값이 달라짐

- 따라서 X_train에서 fit 적용했으면 X_test는 바로 transform 해야 함

- 이를 방지하기 위해 X를 먼저 정규화를 시키고 train과 test로 쪼개는 것이 좋음

### 표준화(Standardization)

- x - mu / sigma 
- 정규분포가 표준정규분포(평균 : 0, 표준편차 : 1)로 변환됨

In [194]:
def standardize(x):
    return (x - x.mean()) / x.std()

In [196]:
iris_df.apply(standardize)

0         1         2         3
0   -0.897674  1.015602 -1.335752 -1.311052
1   -1.139200 -0.131539 -1.335752 -1.311052
2   -1.380727  0.327318 -1.392399 -1.311052
3   -1.501490  0.097889 -1.279104 -1.311052
4   -1.018437  1.245030 -1.335752 -1.311052
..        ...       ...       ...       ...
145  1.034539 -0.131539  0.816859  1.443994
146  0.551486 -1.278680  0.703564  0.919223
147  0.793012 -0.131539  0.816859  1.050416
148  0.430722  0.786174  0.930154  1.443994
149  0.068433 -0.131539  0.760211  0.788031

[150 rows x 4 columns]

In [197]:
iris_df.apply(standardize).mean()

0   -5.684342e-16
1   -7.815970e-16
2   -2.842171e-16
3   -3.789561e-16
dtype: float64

In [199]:
## 방법 2
from sklearn.preprocessing import StandardScaler

In [201]:
s_scaler = StandardScaler()

s_scaler.fit(iris_df)
iris_s_scaled = s_scaler.transform(iris_df)
iris_s_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      